/*
Enter custom T-SQL here that would run after SQL Server has started up. 
*/

ALTER LOGIN SA WITH PASSWORD='admin@1234';
GO
CREATE DATABASE FILE2DB;
GO
CREATE TABLE FILE2DB.dbo.FILE2DBDATA(ID INT IDENTITY NOT NULL PRIMARY KEY, DATA VARCHAR(MAX) NOT NULL);
GO