# stage 1 - builder
# Base golang image with latest go version
FROM golang:1.23.1 AS builder

# set working directory inside container
WORKDIR /go/app/

# copy everything from current directory from host to workimng directory inside container
# this will ignore few files specified in .dockerignore file
COPY ./src .

# set the TimeZone env variable, so that the logs will have IST time
ENV TZ="Asia/Kolkata"

# build the go code inside container
# this will generate executale "datainputapp" into output directory
RUN go build -v -o ./ .

# till here build artifactory/executables have been created

# stage 2 - final
# Lets start final stage
FROM builder AS final

# copy executable from builder stage's output directory into current directory of final stage
COPY --from=builder /go/app/datainputapp /

# Exposing port
EXPOSE 3400

# command to execute the application
CMD [ "./datainputapp" ]
